name: monster
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  ###### ================ UI ================= ######
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  toastification: ^2.3.0


  ###### ================ DATA SOURCE ================= ######
  hive: ^2.2.3
  hive_flutter: ^1.1.0 

  ###### ================ FIREBASE ================= ######
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.5

  ###### ================ UTILS ================= ######
  localize_and_translate: ^6.0.7
  file_picker: ^8.3.1
  image_picker: ^1.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1
  change_app_package_name: 

  # -------- App Icon Launcher ----------#
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Black.ttf
  #       - asset: assets/fonts/Poppins-BlackItalic.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: assets/fonts/Poppins-BoldItalic.ttf
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #       - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
  #       - asset: assets/fonts/Poppins-ExtraLight.ttf
  #       - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #       - asset: assets/fonts/Poppins-Light.ttf
  #       - asset: assets/fonts/Poppins-LightItalic.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-MediumItalic.ttf
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
  #       - asset: assets/fonts/Poppins-Thin.ttf
  #       - asset: assets/fonts/Poppins-ThinItalic.ttf